### ISSUE TITLE
grove_temperature_humidity_sensor.py

### ISSUE THREAD

**Issue by Desseres** [Seeed-Studio/grove.py#10]
Hey, why is this code not on the master branch? 
https://github.com/Seeed-Studio/grove.py/blob/8205879e6e96be4f9c9159b01c347ce1be1be2e5/grove/grove_temperature_humidity_sensor.py

The sensor documentation refers to non-existing files.
http://wiki.seeedstudio.com/Grove-TemperatureAndHumidity_Sensor/

The DHT11 sensor cannot be tested without this example.

**Comment by Pillar1989** [comment]
The wiki document neeed update, I'll push for it.

**Comment by Pillar1989** [comment]
All our documents and introductions have been updated, I believe there is no problem in this aspect now, please test again, thank you!
