### ISSUE TITLE
"grove_temperature_humidity_sensor" command is not found.

### ISSUE THREAD

**Issue by tatsu1225** [Seeed-Studio/grove.py#13]
I want to use Temperature & Humidity Sensor(DHT11).

I installed grove.py following the steps.
But [grove_temperature_humidity_sensor] Command is not found.
Also, I can't find the source code(grove_temperature_humidity_sensor.py).

[grove_temperature_humidity_bme680] Command and [grove_temperature_humidity_sht31] Command can be confirmed.

Please let us know if you know why it doesn't work.
Thank you very much.

**Comment by Pillar1989** [comment]
@tatsu1225  https://github.com/Seeed-Studio/grove.py/commit/6ad60076f8acc2b0523f6fc762259b5cf106ab56
According to the commit, DHT11's library is here. 
https://github.com/Seeed-Studio/Seeed_Python_DHT

**Comment by tatsu1225** [comment]
thanks!!
