### ISSUE TITLE
curl installation fails due to libmraa1 and libbma456

### ISSUE THREAD

**Issue by fjp** [Seeed-Studio/grove.py#14]
When I try to use the online option (curl) to install grove.py I get the following error:

```
fjp@ubuntu:~/git/grove.py$ curl -sL https://github.com/Seeed-Studio/grove.py/raw/master/install.sh | sudo bash -s -
Warning: apt-key output should not be parsed (stdout is not a terminal)
Hit:1 http://ports.ubuntu.com/ubuntu-ports bionic InRelease
Hit:2 http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease                                       
Hit:3 http://ports.ubuntu.com/ubuntu-ports bionic-backports InRelease                                     
Hit:4 http://ports.ubuntu.com/ubuntu-ports bionic-security InRelease                
Hit:5 https://seeed-studio.github.io/pi_repo stretch InRelease                      
Hit:6 http://ports.ubuntu.com/ubuntu-ports bionic-proposed InRelease
Hit:7 http://ppa.launchpad.net/oibaf/graphics-drivers/ubuntu bionic InRelease
Hit:8 http://packages.ros.org/ros/ubuntu bionic InRelease     
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
N: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'https://seeed-studio.github.io/pi_repo stretch InRelease' doesn't support architecture 'arm64'
Enable I2C interface ...
I2C interface enabled...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-rpi.gpio is already the newest version (0.6.3-1ubuntu4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-rpi.gpio is already the newest version (0.6.3-1ubuntu4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libmraa1
dpkg-query: package 'libmraa1' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libmraa1
dpkg-query: package 'libmraa1' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libmraa1
dpkg-query: package 'libmraa1' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
-------------------------------------------------------
     Grove.py installation FAILED, FAILED, FAILED      
-------------------------------------------------------
```

I think this happens because `libmraa1` cannot be located. 

Installing libmraa from [here](https://github.com/intel-iot-devkit/mraa#installing-on-ubuntu) with the following commands:

```
sudo add-apt-repository ppa:mraa/mraa
sudo apt-get update
sudo apt-get install libmraa2 libmraa-dev libmraa-java python-mraa python3-mraa node-mraa mraa-tools
```

After that, I executed the curl command again and got a little further but the installation of grove.py stilll fails because of `libbma456`:

```
fjp@ubuntu:~/git/grove.py$ curl -sL https://github.com/Seeed-Studio/grove.py/raw/master/install.sh | sudo bash -s -
Warning: apt-key output should not be parsed (stdout is not a terminal)
Hit:1 http://ports.ubuntu.com/ubuntu-ports bionic InRelease
Get:2 http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease [88.7 kB]                             
Hit:3 https://seeed-studio.github.io/pi_repo stretch InRelease                                                       
Get:4 http://ports.ubuntu.com/ubuntu-ports bionic-backports InRelease [74.6 kB]
Get:5 http://ports.ubuntu.com/ubuntu-ports bionic-security InRelease [88.7 kB]
Get:6 http://ports.ubuntu.com/ubuntu-ports bionic-proposed InRelease [242 kB]
Get:7 http://ports.ubuntu.com/ubuntu-ports bionic-updates/main arm64 DEP-11 Metadata [290 kB]
Get:8 http://ports.ubuntu.com/ubuntu-ports bionic-updates/main DEP-11 48x48 Icons [73.8 kB]
Get:9 http://ports.ubuntu.com/ubuntu-ports bionic-updates/main DEP-11 64x64 Icons [147 kB]     
Get:10 http://ports.ubuntu.com/ubuntu-ports bionic-updates/universe arm64 DEP-11 Metadata [259 kB]
Get:11 http://ports.ubuntu.com/ubuntu-ports bionic-updates/universe DEP-11 48x48 Icons [207 kB]     
Get:12 http://ports.ubuntu.com/ubuntu-ports bionic-updates/universe DEP-11 64x64 Icons [445 kB]
Get:13 http://ports.ubuntu.com/ubuntu-ports bionic-backports/universe arm64 DEP-11 Metadata [7976 B]
Get:14 http://ports.ubuntu.com/ubuntu-ports bionic-security/main arm64 DEP-11 Metadata [32.6 kB]
Get:15 http://ports.ubuntu.com/ubuntu-ports bionic-security/main DEP-11 48x48 Icons [17.6 kB]
Get:16 http://ports.ubuntu.com/ubuntu-ports bionic-security/main DEP-11 64x64 Icons [41.5 kB]
Get:17 http://ports.ubuntu.com/ubuntu-ports bionic-security/universe arm64 DEP-11 Metadata [37.0 kB]
Get:18 http://ports.ubuntu.com/ubuntu-ports bionic-security/universe DEP-11 48x48 Icons [16.4 kB]
Get:19 http://ports.ubuntu.com/ubuntu-ports bionic-security/universe DEP-11 64x64 Icons [111 kB]  
Get:20 http://ports.ubuntu.com/ubuntu-ports bionic-proposed/main arm64 DEP-11 Metadata [4612 B] 
Get:21 http://ports.ubuntu.com/ubuntu-ports bionic-proposed/universe arm64 DEP-11 Metadata [212 B]
Hit:22 http://ppa.launchpad.net/mraa/mraa/ubuntu bionic InRelease                                                                                                                        
Hit:23 http://ppa.launchpad.net/oibaf/graphics-drivers/ubuntu bionic InRelease                                                                                                           
Hit:24 http://packages.ros.org/ros/ubuntu bionic InRelease                                                                                                                               
Fetched 2185 kB in 11s (198 kB/s)                                                                                                                                                        
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
N: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'https://seeed-studio.github.io/pi_repo stretch InRelease' doesn't support architecture 'arm64'
I2C interface enabled...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-rpi.gpio is already the newest version (0.6.3-1ubuntu4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-rpi.gpio is already the newest version (0.6.3-1ubuntu4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  libmraa1
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 59.1 kB of archives.
After this operation, 179 kB of additional disk space will be used.
Get:1 http://ppa.launchpad.net/mraa/mraa/ubuntu bionic/main arm64 libmraa1 arm64 1.9.0-1~ubuntu18.04 [59.1 kB]
Fetched 59.1 kB in 10s (5800 B/s)   
Selecting previously unselected package libmraa1.
(Reading database ... 211870 files and directories currently installed.)
Preparing to unpack .../libmraa1_1.9.0-1~ubuntu18.04_arm64.deb ...
Unpacking libmraa1 (1.9.0-1~ubuntu18.04) ...
Setting up libmraa1 (1.9.0-1~ubuntu18.04) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-mraa is already the newest version (2.0.0-1~ubuntu18.04).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libupm1
The following NEW packages will be installed:
  libupm1 python-upm
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 3962 kB of archives.
After this operation, 39.3 MB of additional disk space will be used.
Get:1 http://ppa.launchpad.net/mraa/mraa/ubuntu bionic/main arm64 libupm1 arm64 1.7.1-1~ubuntu18.04 [656 kB]
Get:2 http://ppa.launchpad.net/mraa/mraa/ubuntu bionic/main arm64 python-upm arm64 1.7.1-1~ubuntu18.04 [3307 kB]
Fetched 3962 kB in 11s (352 kB/s)     
Selecting previously unselected package libupm1.
(Reading database ... 211875 files and directories currently installed.)
Preparing to unpack .../libupm1_1.7.1-1~ubuntu18.04_arm64.deb ...
Unpacking libupm1 (1.7.1-1~ubuntu18.04) ...
Selecting previously unselected package python-upm.
Preparing to unpack .../python-upm_1.7.1-1~ubuntu18.04_arm64.deb ...
Unpacking python-upm (1.7.1-1~ubuntu18.04) ...
Setting up libupm1 (1.7.1-1~ubuntu18.04) ...
Setting up python-upm (1.7.1-1~ubuntu18.04) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-mraa is already the newest version (2.0.0-1~ubuntu18.04).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  python3-upm
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 3264 kB of archives.
After this operation, 33.5 MB of additional disk space will be used.
Get:1 http://ppa.launchpad.net/mraa/mraa/ubuntu bionic/main arm64 python3-upm arm64 1.7.1-1~ubuntu18.04 [3264 kB]
Fetched 3264 kB in 12s (283 kB/s)      
Selecting previously unselected package python3-upm.
(Reading database ... 212946 files and directories currently installed.)
Preparing to unpack .../python3-upm_1.7.1-1~ubuntu18.04_arm64.deb ...
Unpacking python3-upm (1.7.1-1~ubuntu18.04) ...
Setting up python3-upm (1.7.1-1~ubuntu18.04) ...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libbma456
dpkg-query: package 'libbma456' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libbma456
dpkg-query: package 'libbma456' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libbma456
dpkg-query: package 'libbma456' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
-------------------------------------------------------
     Grove.py installation FAILED, FAILED, FAILED      
-------------------------------------------------------
```

I couldn't find out how to install the missing dependency `libbma456`. Any ideas how I can fix this? Thank you!

**Comment by ecobra** [comment]
I had the same problem then I put _sudo_  before the _curl_ and the problem was solved.

**Comment by bigbearishappy** [comment]
> When I try to use the online option (curl) to install grove.py I get the following error:
> 
> ```
> fjp@ubuntu:~/git/grove.py$ curl -sL https://github.com/Seeed-Studio/grove.py/raw/master/install.sh | sudo bash -s -
> Warning: apt-key output should not be parsed (stdout is not a terminal)
> Hit:1 http://ports.ubuntu.com/ubuntu-ports bionic InRelease
> Hit:2 http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease                                       
> Hit:3 http://ports.ubuntu.com/ubuntu-ports bionic-backports InRelease                                     
> Hit:4 http://ports.ubuntu.com/ubuntu-ports bionic-security InRelease                
> Hit:5 https://seeed-studio.github.io/pi_repo stretch InRelease                      
> Hit:6 http://ports.ubuntu.com/ubuntu-ports bionic-proposed InRelease
> Hit:7 http://ppa.launchpad.net/oibaf/graphics-drivers/ubuntu bionic InRelease
> Hit:8 http://packages.ros.org/ros/ubuntu bionic InRelease     
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> All packages are up to date.
> N: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'https://seeed-studio.github.io/pi_repo stretch InRelease' doesn't support architecture 'arm64'
> Enable I2C interface ...
> I2C interface enabled...
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> python-rpi.gpio is already the newest version (0.6.3-1ubuntu4).
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> python3-rpi.gpio is already the newest version (0.6.3-1ubuntu4).
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> E: Unable to locate package libmraa1
> dpkg-query: package 'libmraa1' is not installed and no information is available
> Use dpkg --info (= dpkg-deb --info) to examine archive files,
> and dpkg --contents (= dpkg-deb --contents) to list their contents.
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> E: Unable to locate package libmraa1
> dpkg-query: package 'libmraa1' is not installed and no information is available
> Use dpkg --info (= dpkg-deb --info) to examine archive files,
> and dpkg --contents (= dpkg-deb --contents) to list their contents.
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> E: Unable to locate package libmraa1
> dpkg-query: package 'libmraa1' is not installed and no information is available
> Use dpkg --info (= dpkg-deb --info) to examine archive files,
> and dpkg --contents (= dpkg-deb --contents) to list their contents.
> -------------------------------------------------------
>      Grove.py installation FAILED, FAILED, FAILED      
> -------------------------------------------------------
> ```
> 
> I think this happens because `libmraa1` cannot be located.
> 
> Installing libmraa from [here](https://github.com/intel-iot-devkit/mraa#installing-on-ubuntu) with the following commands:
> 
> ```
> sudo add-apt-repository ppa:mraa/mraa
> sudo apt-get update
> sudo apt-get install libmraa2 libmraa-dev libmraa-java python-mraa python3-mraa node-mraa mraa-tools
> ```
> 
> After that, I executed the curl command again and got a little further but the installation of grove.py stilll fails because of `libbma456`:
> 
> ```
> fjp@ubuntu:~/git/grove.py$ curl -sL https://github.com/Seeed-Studio/grove.py/raw/master/install.sh | sudo bash -s -
> Warning: apt-key output should not be parsed (stdout is not a terminal)
> Hit:1 http://ports.ubuntu.com/ubuntu-ports bionic InRelease
> Get:2 http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease [88.7 kB]                             
> Hit:3 https://seeed-studio.github.io/pi_repo stretch InRelease                                                       
> Get:4 http://ports.ubuntu.com/ubuntu-ports bionic-backports InRelease [74.6 kB]
> Get:5 http://ports.ubuntu.com/ubuntu-ports bionic-security InRelease [88.7 kB]
> Get:6 http://ports.ubuntu.com/ubuntu-ports bionic-proposed InRelease [242 kB]
> Get:7 http://ports.ubuntu.com/ubuntu-ports bionic-updates/main arm64 DEP-11 Metadata [290 kB]
> Get:8 http://ports.ubuntu.com/ubuntu-ports bionic-updates/main DEP-11 48x48 Icons [73.8 kB]
> Get:9 http://ports.ubuntu.com/ubuntu-ports bionic-updates/main DEP-11 64x64 Icons [147 kB]     
> Get:10 http://ports.ubuntu.com/ubuntu-ports bionic-updates/universe arm64 DEP-11 Metadata [259 kB]
> Get:11 http://ports.ubuntu.com/ubuntu-ports bionic-updates/universe DEP-11 48x48 Icons [207 kB]     
> Get:12 http://ports.ubuntu.com/ubuntu-ports bionic-updates/universe DEP-11 64x64 Icons [445 kB]
> Get:13 http://ports.ubuntu.com/ubuntu-ports bionic-backports/universe arm64 DEP-11 Metadata [7976 B]
> Get:14 http://ports.ubuntu.com/ubuntu-ports bionic-security/main arm64 DEP-11 Metadata [32.6 kB]
> Get:15 http://ports.ubuntu.com/ubuntu-ports bionic-security/main DEP-11 48x48 Icons [17.6 kB]
> Get:16 http://ports.ubuntu.com/ubuntu-ports bionic-security/main DEP-11 64x64 Icons [41.5 kB]
> Get:17 http://ports.ubuntu.com/ubuntu-ports bionic-security/universe arm64 DEP-11 Metadata [37.0 kB]
> Get:18 http://ports.ubuntu.com/ubuntu-ports bionic-security/universe DEP-11 48x48 Icons [16.4 kB]
> Get:19 http://ports.ubuntu.com/ubuntu-ports bionic-security/universe DEP-11 64x64 Icons [111 kB]  
> Get:20 http://ports.ubuntu.com/ubuntu-ports bionic-proposed/main arm64 DEP-11 Metadata [4612 B] 
> Get:21 http://ports.ubuntu.com/ubuntu-ports bionic-proposed/universe arm64 DEP-11 Metadata [212 B]
> Hit:22 http://ppa.launchpad.net/mraa/mraa/ubuntu bionic InRelease                                                                                                                        
> Hit:23 http://ppa.launchpad.net/oibaf/graphics-drivers/ubuntu bionic InRelease                                                                                                           
> Hit:24 http://packages.ros.org/ros/ubuntu bionic InRelease                                                                                                                               
> Fetched 2185 kB in 11s (198 kB/s)                                                                                                                                                        
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> All packages are up to date.
> N: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'https://seeed-studio.github.io/pi_repo stretch InRelease' doesn't support architecture 'arm64'
> I2C interface enabled...
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> python-rpi.gpio is already the newest version (0.6.3-1ubuntu4).
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> python3-rpi.gpio is already the newest version (0.6.3-1ubuntu4).
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> The following NEW packages will be installed:
>   libmraa1
> 0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
> Need to get 59.1 kB of archives.
> After this operation, 179 kB of additional disk space will be used.
> Get:1 http://ppa.launchpad.net/mraa/mraa/ubuntu bionic/main arm64 libmraa1 arm64 1.9.0-1~ubuntu18.04 [59.1 kB]
> Fetched 59.1 kB in 10s (5800 B/s)   
> Selecting previously unselected package libmraa1.
> (Reading database ... 211870 files and directories currently installed.)
> Preparing to unpack .../libmraa1_1.9.0-1~ubuntu18.04_arm64.deb ...
> Unpacking libmraa1 (1.9.0-1~ubuntu18.04) ...
> Setting up libmraa1 (1.9.0-1~ubuntu18.04) ...
> Processing triggers for libc-bin (2.27-3ubuntu1) ...
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> python-mraa is already the newest version (2.0.0-1~ubuntu18.04).
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> The following additional packages will be installed:
>   libupm1
> The following NEW packages will be installed:
>   libupm1 python-upm
> 0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
> Need to get 3962 kB of archives.
> After this operation, 39.3 MB of additional disk space will be used.
> Get:1 http://ppa.launchpad.net/mraa/mraa/ubuntu bionic/main arm64 libupm1 arm64 1.7.1-1~ubuntu18.04 [656 kB]
> Get:2 http://ppa.launchpad.net/mraa/mraa/ubuntu bionic/main arm64 python-upm arm64 1.7.1-1~ubuntu18.04 [3307 kB]
> Fetched 3962 kB in 11s (352 kB/s)     
> Selecting previously unselected package libupm1.
> (Reading database ... 211875 files and directories currently installed.)
> Preparing to unpack .../libupm1_1.7.1-1~ubuntu18.04_arm64.deb ...
> Unpacking libupm1 (1.7.1-1~ubuntu18.04) ...
> Selecting previously unselected package python-upm.
> Preparing to unpack .../python-upm_1.7.1-1~ubuntu18.04_arm64.deb ...
> Unpacking python-upm (1.7.1-1~ubuntu18.04) ...
> Setting up libupm1 (1.7.1-1~ubuntu18.04) ...
> Setting up python-upm (1.7.1-1~ubuntu18.04) ...
> Processing triggers for libc-bin (2.27-3ubuntu1) ...
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> python3-mraa is already the newest version (2.0.0-1~ubuntu18.04).
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> The following NEW packages will be installed:
>   python3-upm
> 0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
> Need to get 3264 kB of archives.
> After this operation, 33.5 MB of additional disk space will be used.
> Get:1 http://ppa.launchpad.net/mraa/mraa/ubuntu bionic/main arm64 python3-upm arm64 1.7.1-1~ubuntu18.04 [3264 kB]
> Fetched 3264 kB in 12s (283 kB/s)      
> Selecting previously unselected package python3-upm.
> (Reading database ... 212946 files and directories currently installed.)
> Preparing to unpack .../python3-upm_1.7.1-1~ubuntu18.04_arm64.deb ...
> Unpacking python3-upm (1.7.1-1~ubuntu18.04) ...
> Setting up python3-upm (1.7.1-1~ubuntu18.04) ...
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> E: Unable to locate package libbma456
> dpkg-query: package 'libbma456' is not installed and no information is available
> Use dpkg --info (= dpkg-deb --info) to examine archive files,
> and dpkg --contents (= dpkg-deb --contents) to list their contents.
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> E: Unable to locate package libbma456
> dpkg-query: package 'libbma456' is not installed and no information is available
> Use dpkg --info (= dpkg-deb --info) to examine archive files,
> and dpkg --contents (= dpkg-deb --contents) to list their contents.
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> E: Unable to locate package libbma456
> dpkg-query: package 'libbma456' is not installed and no information is available
> Use dpkg --info (= dpkg-deb --info) to examine archive files,
> and dpkg --contents (= dpkg-deb --contents) to list their contents.
> -------------------------------------------------------
>      Grove.py installation FAILED, FAILED, FAILED      
> -------------------------------------------------------
> ```
> 
> I couldn't find out how to install the missing dependency `libbma456`. Any ideas how I can fix this? Thank you!

Hello, this command works fine now. 
Closing the issue~
