### ISSUE TITLE
Infrared Temperature Sensor / MLX90615

### ISSUE THREAD

**Issue by WirthmU** [Seeed-Studio/grove.py#25]
I could not find any information about the Infrared Temperature Sensor (MLX90615).

Did anyone made this running on a RPI?

**Comment by tyihuang** [comment]
https://wiki.seeedstudio.com/Grove-Infrared_Temperature_Sensor/

**Comment by is-qian** [comment]
Currently, MLX90615 is not supported. If you want to learn more about this sensor, you can refer to [here](https://wiki.seeedstudio.com/Grove-Digital_Infrared_Temperature_Sensor).
