### ISSUE TITLE
Trouble installing grove.py

### ISSUE THREAD

**Issue by grantforster1979** [Seeed-Studio/grove.py#28]
Hello,

I've been playing around with an OKdo Air Quality kit and I seem to have fallen at an early hurdle.

The installation of grove.py on to a Pi using the command below seems to go well until the very end where I am told that the installation failed.

curl -sL https://github.com/Seeed-Studio/grove.py/raw/master/install.sh | sudo bash -s -

main: line 107: pip: command not found
main: line 108: pip: command not found
main: line 107: pip: command not found
main: line 108: pip: command not found
main: line 107: pip: command not found
main: line 108: pip: command not found
-------------------------------------------------------
     Grove.py installation FAILED, FAILED, FAILED

Any thoughts on how to solve this would be awesome.

regards,

**Comment by tang295** [comment]
I got this too, it turns out their install.sh is trying to run the older python2 pip, so unfortunately you will need to install it

sudo apt-get install python-pip

and then it will work. Hopefully they will fix this and in the future it will only need python3-pip.
