### ISSUE TITLE
ADC.version() - wrong implementation for register 0x03

### ISSUE THREAD

**Issue by pezi** [Seeed-Studio/grove.py#29]
`    @property
     def version(self):
     return self.read_register(0x3)
`

Reading from this register doesn' t return a firmware version - int value. 
Reapeated reading from this register returns following string: 
GROVE BASE HAT RPI

**Comment by turmary** [comment]
If you want know more, he grove base hat rpi firmware source:
https://github.com/Seeed-Studio/grove_stm32f030/blob/master/1.0.0/libraries/GroveSTM32F030/examples/grove_rpi_base_hat/grove_rpi_base_hat.ino

**Comment by turmary** [comment]
Will close this issue, please open a new issue if you have further questions.
