### ISSUE TITLE
grove_gesture_sensor.py differs from Arduino C Code

### ISSUE THREAD

**Issue by pezi** [Seeed-Studio/grove.py#33]
https://github.com/Seeed-Studio/grove.py/blob/master/grove/grove_gesture_sensor.py

``` python
		if data0 != 0x20  :#or data1 <> 0x76:
			print("Error with sensor")
		
```
Only one byte is checked - second check is commted out. Why?

``` python
if data == self.GES_FORWARD_FLAG:
				return 1
				time.sleep(self.GES_QUIT_TIME) 
```

Multiple dead code statments after return?

```  C
 } else if (data == GES_FORWARD_FLAG) {
                    Serial.println("Forward");
                    delay(GES_QUIT_TIME);
}

**Comment by is-qian** [comment]
Thanks for your suggestion. The dead code has been removed [here](https://github.com/Seeed-Studio/grove.py/commit/1467b179fd0a1d85d210b0c991f8fca004be73f9).
