### ISSUE TITLE
Support for grove led bar on Grove Base Hat

### ISSUE THREAD

**Issue by glamorous** [Seeed-Studio/grove.py#39]
Is there a possibility to have a code example for programming the grove led bar?

**Comment by Pillar1989** [comment]
Please help him&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Seeed-Studio/grove.py"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月2日(星期五) 凌晨4:39
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Seeed-Studio/grove.py] Support for grove led bar (#39)





 
Is there a possibility to have a code example for programming the grove led bar?

**Comment by tyihuang** [comment]
You can think of the relevant information and code here
https://wiki.seeedstudio.com/Grove-LED_Bar/

**Comment by glamorous** [comment]
> You can think of the relevant information and code here
> https://wiki.seeedstudio.com/Grove-LED_Bar/

No, that only working when you have the GrovePi, not the Grove Base hat.

**Comment by gmol** [comment]
Same request. Please add an example for Grove LED Bar.

**Comment by glamorous** [comment]
Nobody who can help? 😞

**Comment by gughpatrik619** [comment]
Why is nobody responding? @staff

**Comment by zolgear** [comment]
Forked and added a module.

https://github.com/zolgear/grove.py/blob/master/grove/grove_ledbar.py

I referred to "mcauser/micropython-my9221" and the datasheet.

**Comment by is-qian** [comment]
Currently, there is no update on this aspect. You can try modifying GrovePi to run it. If you get good results, you can submit a pull request to us for testing.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
