### ISSUE TITLE
Support for WS2813 RGB LED strips on Jetson Nano

### ISSUE THREAD

**Issue by bennettmountain** [Seeed-Studio/grove.py#40]
Any idea on if or when this will be available? Or does anyone know of any alternative libraries I can use to connect the Jetson Nano to an LED strip (not just aWS2813 - I'm also looking at using a WS2812 or WS2812B)

**Comment by is-qian** [comment]
Currently, there is no support for Jetson Nano, so you may need to make some modifications if you want to use it. If you encounter any problems during use, feel free to continue to raise them.
