### ISSUE TITLE
GPS module only reads US satellites

### ISSUE THREAD

**Issue by jimbobbennett** [Seeed-Studio/grove.py#42]
In the [GPS module code](https://github.com/Seeed-Studio/grove.py/blob/master/grove/modules/gps/__init__.py), the only source that is detected is `GP`, the US GPS constellation. The Air530 sensor supports other constellations, but this library is unable to detect them.

The logic in the [`read` function](https://github.com/Seeed-Studio/grove.py/blob/master/grove/modules/gps/__init__.py#L111-L118) should ignore the 2 characters for the sender field at the start of the NMEA message to support other constellations.

**Comment by Pillar1989** [comment]
Thanks
