### ISSUE TITLE
Can't install Grove lib on Jetson Nano

### ISSUE THREAD

**Issue by KristinSpatial** [Seeed-Studio/grove.py#45]
Hi, I'm getting some permissions errors I can't seem to resolve on my own when running curl -sL https://github.com/Seeed-Studio/grove.py/raw/master/install.sh | sudo bash -s –
I've tried running the curl command as root, and setting sudo's -H flag as the error message suggests, but still got the following errors. Was wondering if you had suggestions for getting around what appears to be user conflicts between user root and my user? 

-----------------------------------------------
...
 upgraded, 0 newly installed, 0 to remove and 53 not upgraded.
**The directory '/home/kristin/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/kristin/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.**
Collecting smbus
  Downloading https://files.pythonhosted.org/packages/4d/5c/70e14aa4f0c586efc017e1d1aa6e2f7921eefc7602fc2d03368ff912aa91/smbus-1.1.post2.tar.gz (104kB)
    100% |████████████████████████████████| 112kB 1.6MB/s 
Installing collected packages: smbus
  Running setup.py install for smbus ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-9ddcdzvv/smbus/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-cuxgtx1g-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'i2c' library
    b''
    building 'smbus' extension
    creating build
    creating build/temp.linux-aarch64-3.7
    aarch64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.7m -c smbusmodule.c -o build/temp.linux-aarch64-3.7/smbusmodule.o -Iinclude
    smbusmodule.c:20:10: fatal error: Python.h: No such file or directory
     #include <Python.h>
              ^~~~~~~~~~
    compilation terminated.
    **error: command 'aarch64-linux-gnu-gcc' failed with exit status 1**
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-9ddcdzvv/smbus/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-cuxgtx1g-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-9ddcdzvv/smbus/
**The directory '/home/kristin/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/kristin/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.**
Collecting smbus
  Downloading https://files.pythonhosted.org/packages/4d/5c/70e14aa4f0c586efc017e1d1aa6e2f7921eefc7602fc2d03368ff912aa91/smbus-1.1.post2.tar.gz (104kB)
    100% |████████████████████████████████| 112kB 1.9MB/s 
Installing collected packages: smbus
  Running setup.py install for smbus ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-4bystfwg/smbus/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-o4ar8ut6-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'i2c' library
    b''
    building 'smbus' extension
    creating build
    creating build/temp.linux-aarch64-3.7
    aarch64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.7m -c smbusmodule.c -o build/temp.linux-aarch64-3.7/smbusmodule.o -Iinclude
    smbusmodule.c:20:10: fatal error: Python.h: No such file or directory
     #include <Python.h>
              ^~~~~~~~~~
    compilation terminated.
    error: command 'aarch64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-4bystfwg/smbus/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-o4ar8ut6-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-4bystfwg/smbus/
**The directory '/home/kristin/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/kristin/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.**
Collecting smbus
  Downloading https://files.pythonhosted.org/packages/4d/5c/70e14aa4f0c586efc017e1d1aa6e2f7921eefc7602fc2d03368ff912aa91/smbus-1.1.post2.tar.gz (104kB)
    100% |████████████████████████████████| 112kB 2.1MB/s 
Installing collected packages: smbus
  Running setup.py install for smbus ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-8lpoao6f/smbus/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ki5y2f3q-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'i2c' library
    b''
    building 'smbus' extension
    creating build
    creating build/temp.linux-aarch64-3.7
    aarch64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.7m -c smbusmodule.c -o build/temp.linux-aarch64-3.7/smbusmodule.o -Iinclude
    **smbusmodule.c:20:10: fatal error: Python.h: No such file or directory**
     #include <Python.h>
              ^~~~~~~~~~
    compilation terminated.
    error: command 'aarch64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-8lpoao6f/smbus/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ki5y2f3q-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-8lpoao6f/smbus/
-------------------------------------------------------
     Grove.py installation FAILED, FAILED, FAILED

**Comment by is-qian** [comment]
Currently the latest version (0.8) does not support Jetson Nano yet, so you may need to make some modifications if you want to use it. If you encounter any problems during use, feel free to continue to raise them.
