### ISSUE TITLE
Grove-Sunlight_Sensor Missing

### ISSUE THREAD

**Issue by duart38** [Seeed-Studio/grove.py#60]
https://wiki.seeedstudio.com/Grove-Sunlight_Sensor/

**Comment by is-qian** [comment]
Could you please elaborate on the issues you encountered after following the wiki instructions? The repository for Grove-Sunlight_Sensor is located [here](https://github.com/Seeed-Studio/Seeed_Python_SI114X). Without further information, I will close this issue.
