### ISSUE TITLE
ADC of Grove Base Hat not working with reTerminal

### ISSUE THREAD

**Issue by maubuz** [Seeed-Studio/grove.py#64]
The analog to digital converter (ADC) of the [https://wiki.seeedstudio.com/Grove_Base_Hat_for_Raspberry_Pi/](Grove Base Hat for Raspberry Pi) is no longer working after [commit a4a5c9b](https://github.com/Seeed-Studio/grove.py/commit/a4a5c9bb00aa2bb5ee6d6d50098d6ddc05346140).

To get it working, the i2c address `0x04` must be explicitly passed to the ADC class constructor:

```python
from grove.adc import ADC
adc = ADC(address = 0x04)
```

My understanding is that Seeed is prioritizing a new default micro-controller for the Base Hat (change from STM32 to MM32). However, it is important to clearly inform those who have the STM32 Base Hat of the changes and how to get it working.

I suggest adding a note to the `adc.py` module and a note on the Base Hat's Wiki page.

**Comment by is-qian** [comment]
Yes, it's because the i2c address 0x0 is not available in mm32. Now it has been switched back to stm32, and I will note this problem on the wiki later.
