### ISSUE TITLE
Support for Raspberry Pi Pico W with RP2040

### ISSUE THREAD

**Issue by mores** [Seeed-Studio/grove.py#69]
Can the Raspberry Pi Pico utilize grove.py ?

If so, how does one install it ?

If not, is there a different repository to look at ?

**Comment by mores** [comment]
I have working code for grove_ultrasonic_ranger.py MicroPython.
Now I just need to find out the best location to publish it to.

**Comment by mores** [comment]
Here is a Python class that works on RP2040 board using microPython: https://github.com/mores/TheMissingLink/tree/main/Seeed_MicroPython_UltrasonicRanger

**Comment by is-qian** [comment]
Currently, it does not support micropython, and this repository has only been tested on raspbianOS.
