### ISSUE TITLE
pyton impl for Grove - Sunlight sensor SI1151

### ISSUE THREAD

**Issue by tim-oe** [Seeed-Studio/grove.py#79]
looking to see if there's an existing python lib for
https://www.seeedstudio.com/Grove-Sunlight-Sensor.html

**Comment by is-qian** [comment]
Is [this](https://github.com/Seeed-Studio/Seeed_Python_SI114X) what you're probably looking for?

**Comment by tim-oe** [comment]
i haven't get the sensor yet was wanting to verify the libe first.
I'll give it a shot not too expensive.

**Comment by is-qian** [comment]
This [commit ](https://github.com/Seeed-Studio/grove.py/commit/b00086275eafe1e69a5231e65995153cf4b78a29)has already added si115x.
